### PR TITLE
Add option to force ongoing notifications

### PR DESCRIPTION
**Pull request by GermainZ**
The app settings activity is getting really crowded. :)

### CODE REVIEW

**Comment by Tungstwenty** [comment]
What is the purpose of this setting? Preventing dismissing the notifications?

**Comment by GermainZ** [comment]
Yes, exactly.
On Wed, Aug 13, 2014 at 2:27 PM, Tungstwenty notifications@github.com wrote:What is the purpose of this setting? Preventing dismissing the notifications?

**Comment by Tungstwenty** [comment]
I'm not sure if it's such a useful feature, especially considering that it's already very crowded indeed :)
Do you have a particular use case for this?

**Comment by GermainZ** [comment]
I personally use it for Bytes Insight and the alarm clock (useful for "Upcoming alarm" notifications, as those can be cleared if there's 1-2h left until the alarm).
Something like this was also recently [requested on reddit](http://www.reddit.com/r/androidapps/comments/2cpm30/_/), the use case there was for Google Now notifications.
On Wed, Aug 13, 2014 at 4:20 PM, Tungstwenty notifications@github.com wrote:I'm not sure if it's such a useful feature, especially considering that it's already very crowded indeed :)
Do you have a particular use case for this?

**Comment by Tungstwenty** [comment]
I opted to implement a Force/Prevent option for this, since there are also some situations where it's useful to disable the behavior (see commit e773a1f2b0aab68afcd58a62e7bd4128b6063ec1)

**Pull request closed without merging**
