### PR TITLE
ViewHolder + indeed

### PR DESCRIPTION
**Pull request by Dzakus**
Is the correct indentation is good? Polite/Kindly?

### CODE REVIEW

**Comment by Dzakus** [comment]
What do you think about AsyncTaskLoader or/and move SearchView to ActionBar?

**Comment by Dzakus** [comment]
I have tested the patch for a few days. I did not notice problems. The list scrolls much smoother. Earlier lags sometimes lasting more than 2 seconds. 
No confusing icons. No forced closures.

**Comment by rovo89** [comment]
Using the ViewHolder should be fine. But why did you make the filter lazy-loading? I see no reason for that.

The space to tabs changes are ok as well, except that there are still some things that should be corrected (e.g. trailing spaces, empty lines shouldn't have any whitespace). I can try if using Ctrl+I with my style fixes that.

In the third commit, you actually introduce some other code style again, but I can correct that myself. I'm not sure whether AsyncTask is correct here as I haven't used it before. I'm afraid it might display the wrong icon if the AsyncTask takes a bit longer and the view already displays a different package.

**Comment by Dzakus** [comment]
AsyncTask is good because I compare position before set.

For other issues will reply later, because I'm tired and have only phone.

**Comment by Dzakus** [comment]
http://developer.android.com/training/improving-layouts/smooth-scrolling.html

**Comment by Dzakus** [comment]
> Using the ViewHolder should be fine. But why did you make the filter lazy-loading? I see no reason for that.

To avoid create new object when sb type text in SearchView. "Every class instance has 12-16 bytes of RAM overhead."
http://developer.android.com/training/articles/memory.html

> In the third commit, you actually introduce some other code style again, but I can correct that myself. 

Do you mean mInflater instead inflater? Sorry. Too late I realized.

**Comment by rovo89** [comment]
I don't see any relation between the search function and the constructor of the AppListAdapter. Anyway, 12-16 bytes of RAM is nothing, so I'll leave out that change.

With the code style, I mean that there are spaces instead of tabs, no space between the "if" and the bracket etc. But I will take care of this before merging it.

**Comment by rovo89** [comment]
I ended up correction the indention first, then applying your changes. I also chose to cancel the AsyncTask as soon as it's no longer valid.

**Pull request closed without merging**
