### PR TITLE
Added immersive mode to App Settings fullscreen mode

### PR DESCRIPTION
**Pull request by MohammadAG**
Basically this http://forum.xda-developers.com/showthread.php?t=2557697 but configurable :)

### CODE REVIEW

**Comment by rovo89** [comment]
Thanks, I hope that I can test it today.

**Comment by rovo89** [comment]
Sorry, still didn't have the time for it and my Nexus is currently focused on ART. ;)

**Comment by MohammadAG** [comment]
No worries, is that Xposed support for ART or simply having a look at it? :P

**Comment by rovo89** [comment]
Xposed support for ART. :) I have already spent some dozen hours on that. This evening, I spent another 5 hours to debug the garbage collector which free'd some variables that were still in use. It was a copy and paste error on my side, making not only the hooked method native, but also the backup of the original method which is called later. :( Now most standard hooks are working, but still lots of tests (especially of edge cases), optimizations, cleanups etc. are necessary before I can provide an experimental version.

**Comment by MohammadAG** [comment]
Wow, I'm honestly surprised you got it working this quick. I was almost sure it would've taken till ART was standardized or after.
I'd love to help out, but I have no ART-enabled devices, the 2012 Nexus 7 doesn't come with that option apparently...

Good work nonetheless :)

**Comment by berserker** [comment]
Nice work MohammadAG!
I was looking for that ;)

**Comment by rovo89** [comment]
It's working fine for me, although I wouldn't want to use immersive mode all the time. Often I simply need the navigation. I made some minor changes, especially I bumped the target API to make the new flags available at compile time.

**Comment by berserker** [comment]
Hope to see a release with this patch soon :D

**Comment by rovo89** [comment]
Only @Tungstwenty has the correct keys to sign the App Settings APK.

**Comment by Tungstwenty** [comment]
@berserker, you can grab version 1.7 which includes this new feature.

**Comment by tonyp** [comment]
@rovo89 @MohammadAG @Tungstwenty 
This is excellent, I've enabled it for a couple apps which don't yet support immersive mode. Especially useful for games I suppose.
I did notice one issue though: when i use the recent apps screen to leave and go back into the app the navbar won't fade out anymore, causing it to overlay the app until it's restarted.
Can you confirm?

**Comment by berserker** [comment]
@Tungstwenty 
Thanks! I'm already testing it and it's great ;)
I'm expecting only some issues as reported by @tonyp (i.e.: a simple change to the "audio volume" causes the immersive mode to be lost).

**Comment by rovo89** [comment]
This has been reported in the thread a couple of times and MohammadAG said he will look at it: http://forum.xda-developers.com/showthread.php?p=48564763#post48564763

**Comment by Dzakus** [comment]
My fix:

``` java
package pl.com.android.uimode;

import android.app.Dialog;
import android.view.Window;
import android.view.WindowManager.LayoutParams;
import de.robv.android.xposed.IXposedHookZygoteInit;
import de.robv.android.xposed.XC_MethodHook;
import de.robv.android.xposed.XC_MethodHook.MethodHookParam;
import de.robv.android.xposed.XposedBridge;
import de.robv.android.xposed.XposedHelpers;

public class Xposed implements IXposedHookZygoteInit {

    public static final String CLASS_VOLUME_PANEL = "android.view.VolumePanel";
    public static final int PRIVATE_FLAG_FORCE_SHOW_NAV_BAR = 0x00000020;

    @Override
    public void initZygote(StartupParam startupParam) throws Throwable {

        Class<?> VolumePanelClass = XposedHelpers.findClass(CLASS_VOLUME_PANEL, null);
        XposedBridge.hookAllConstructors(VolumePanelClass, new XC_MethodHook(){

            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                Dialog dialog = (Dialog) XposedHelpers.getObjectField(param.thisObject, "mDialog");
                Window window = dialog.getWindow();
                LayoutParams lp = window.getAttributes();

                //lp.privateFlags &= ~LayoutParams.PRIVATE_FLAG_FORCE_SHOW_NAV_BAR);
                int privateFlags = XposedHelpers.getIntField(lp, "privateFlags");
                privateFlags &= ~PRIVATE_FLAG_FORCE_SHOW_NAV_BAR;
                XposedHelpers.setIntField(lp, "privateFlags", privateFlags);

                window.setAttributes(lp);
            }});
    }
}
```

**Comment by tonyp** [comment]
That's a rather ugly hack and doesn't fix all problems. I think there have
been discussed alternatives in the xda thread.

**Comment by rovo89** [comment]
Yes, here is my suggestion: http://forum.xda-developers.com/showpost.php?p=48576099&postcount=503

**Comment by kevdliu** [comment]
@rovo89 your PhoneWindow$DecorView.onWindowFocusChanged idea is probably the best but im just gonna throw my implementation out there as well. I registered an OnSystemUiVisibilityChangeListener and restore the flags when needed. It's working pretty well here. 

Also, like @tonyp mentioned some games display a black/white bar where the nav bar used to be instead of taking up the whole screen (see screenshot). To solve this you have to return the fullwidth in getNonDecorDisplayWidth() and getNonDecorDisplayHeight() in PhoneWindowManager. I am currently not sure how we can toggle the behavior, maybe by setting an additional static variable? 
screenshot_2013-12-19-19-12-13

**Comment by tonyp** [comment]
@rovo89 @kevdliu @MohammadAG 
I'm not sure if onWindowFocusChanged is necessary or onResume would suffice. Someone would have to test how an app reacts when it's displaying a keyboard in immersive mode.

Oh btw, the documentation example sets a couple more flags in addition to the immersive mode:
https://developer.android.com/training/system-ui/immersive.html#sticky

@kevdliu: actually the fullscreen flag should take care of that, shouldn't it?

**Comment by kevdliu** [comment]
@tonyp it should, but it doesn't. I had to edit PhoneWindowManager for some apps to work properly. 

@rovo89, I don't know why but setAdditionalStaticField() doesn't seem to work with PhoneWindowManager. Or maybe im using it wrong. 

In a hooked method in the Activity class, I used findClass() to find the PhoneWindowManager class and then used setAdditionalStaticField() to set a custom field. However, when I tried to retrieve it in a hooked method in PhoneWindowManager, the field is not set. Not sure what's wrong here. Sorry for the awkard descriptions.

**Comment by rovo89** [comment]
@tonyp I don't have the time to test it at the moment, Christmas preparations are ongoing. ;) I just suggested onWindowFocusChanged() because that is what the documentation suggests. I believe that onPause() and onResume() are not triggered because the activity doesn't change, but I could be wrong.

@kevdliu: Did you try setting all of those flags from the documentation, including the LAYOUT_\* ones? I watched a video where they explained that these flags tell the system to give the app as much space as they would have once it goes fullscreen and the navigation bar is hidden.

Regarding setAdditionalStaticField(): The instance of PhoneWindowManager runs in the system_server process, whereas the Activity runs in the app's process. Different processes, different memory. A variable you set in one process can't be visible in the other process etc.

**Comment by Dzakus** [comment]
https://android.googlesource.com/platform/frameworks/base/+/ca4d040
In Android 4.4.3 Google merged my module from this comment: https://github.com/rovo89/XposedAppSettings/pull/17#issuecomment-30896880

**Pull request closed without merging**
